import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";

const InterSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Captive App",
  description: "Generated by Ming Wei",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterSans.variable}`}>{children}</body>
    </html>
  );
}
